var products = [{
    "Id": 1,
    "Name": "Wireshark",
    "Bought": 30,
    "Stock": 120,
    "Company": "Wireshark inc",
    "Desc": "Packet sniffing software",
    "Duration": "12m",
    "Type": "Scanning",
    "Experience": "Low",
    "Image": "images/wireshark.png",
    "Price": 500.00
},
{
    "Id": 2,
        "Name": "Angry IP scanner",
        "Bought": 50,
        "Stock": 100,
        "Company": "Angry IP Scanner inc",
        "Desc": "IP address & port  scanner ",
        "Duration": "15m",
        "Type": "Scanning",
        "Experience": "Low",
        "Image": "images/Angryip.png",
        "Price": 500.00
},
{
    "Id": 3,
        "Name": "HTTRACK",
        "Bought": 60,
        "Stock": 200,
        "Company": "HTTRACK inc",
        "Desc": "Website cloner ",
        "Duration": "20m",
        "Type": "Scanning",
        "Experience": "medium",
        "Image": "images/HTTRACK.png",
        "Price": 700.00
},
{
    "Id": 4,
        "Name": "Path Analyser pro",
        "Bought": 70,
        "Stock": 100,
        "Company": "Path Analyser Pro inc",
        "Desc": "Detects trusted routers + firewalls ",
        "Duration": "25m",
        "Type": "Scanning",
        "Experience": "Medium",
        "Image": "images/Path_Analyser_pro",
        "Price": 900.00
},
{
    "Id": 5,
        "Name": "HPING3",
        "Bought": 100,
        "Stock": 1000,
        "Company": "HPING3 inc",
        "Desc": "TCP/UDP packet crafting + detects live hosts ",
        "Duration": "50m",
        "Type": "Scanning",
        "Experience": "High",
        "Image": "images/HPING3",
        "Price": 1000.00
},
{
    "Id": 6,
        "Name": "Colasoft Packet Builder",
        "Bought": 1000,
        "Stock": 10000,
        "Company": "Cola soft packet builder inc",
        "Desc": "network & ARP scanning  ",
        "Duration": "60m",
        "Type": "Scanning",
        "Experience": "High",
        "Image": "images/Colasoft_packet_builder",
        "Price": 1000.00
},
{
    "Id": 7,
        "Name": "Mega Ping",
        "Bought": 200,
        "Stock": 1000,
        "Company": "Megaping inc",
        "Desc": " detects live hosts ",
        "Duration": "25m",
        "Type": "Scanning",
        "Experience": "Medium",
        "Image": "images/Mega ping",
        "Price": 450.00


},
{
    "Id": 8,
        "Name": "Mega Ping",
        "Bought": 200,
        "Stock": 1000,
        "Company": "Megaping inc",
        "Desc": " detects live hosts ",
        "Duration": "25m",
        "Type": "Scanning",
        "Experience": "Medium",
        "Image": "images/Mega ping",
        "Price": 450.00
},
{
    "Id": 9,
        "Name": "NMAP",
        "Bought": 200,
        "Stock": 1000,
        "Company": "Megaping inc",
        "Desc": " Packet tracer ",
        "Duration": "25m",
        "Type": "Scanning",
        "Experience": "Medium",
        "Image": "images/NMAP ping",
        "Price": 600.00
},
{
    "Id": 10,
        "Name": "netscan tools pro",
        "Bought": 300,
        "Stock": 1000,
        "Company": "Netscan tools pro inc",
        "Desc": " DHCP discovery , ARP ping  ",
        "Duration": "20m",
        "Type": "Scanning",
        "Experience": "Medium",
        "Image": "images/netscan_tools_pro ping",
        "Price": 300.00
},
{
    "Id": 11,
        "Name": "HTTPrat",
        "Bought": 30,
        "Stock": 100,
        "Company": "HTTPrat inc",
        "Desc": " Remote Access Trojan ",
        "Duration": "20m",
        "Type": "Malware",
        "Experience": "Beginner",
        "Image": "images/HTTPrat ping",
        "Price": 300.00
},
{
    "Id": 12,
        "Name": "MoSucker trojan",
        "Bought": 50,
        "Stock": 1000,
        "Company": "MoSucker Trojan inc",
        "Desc": " Remote Access Trojan ",
        "Duration": "20m",
        "Type": "Malware",
        "Experience": "Medium",
        "Image": "images/MoSucker Trojan ping",
        "Price": 200.00
},
{
    "Id": 13,
        "Name": "Theef",
        "Bought": 100,
        "Stock": 20,
        "Company": "Theef inc",
        "Desc": " Remote Access Trojan ",
        "Duration": "20m",
        "Type": "Malware",
        "Experience": "Medium",
        "Image": "images/Theef ping",
        "Price": 200.00
},

{
    "Id": 14,
        "Name": "JPS Virus Maker",
        "Bought": 200,
        "Stock": 100,
        "Company": "JPS Virus maker inc",
        "Desc": " Remote Access Trojan ",
        "Duration": "20m",
        "Type": "Malware",
        "Experience": "Medium",
        "Image": "images/JPS Virus Maker ping",
        "Price": 300.00
},

{
    "Id": 15,
        "Name": "Internet Worm Maker Thing",
        "Bought": 400,
        "Stock": 300,
        "Company": "Internet Worm Maker Thing inc",
        "Desc": " Remote Access Trojan ",
        "Duration": "20m",
        "Type": "Malware",
        "Experience": "Medium",
        "Image": "images/Internet Worm Maker Thing ping",
        "Price": 300.00


},

{
    "Id": 16,
        "Name": "Currports",
        "Bought": 200,
        "Stock": 100,
        "Company": "Currports inc",
        "Desc": " Kills suspicous processes ",
        "Duration": "20m",
        "Type": "Security Tool",
        "Experience": "Medium",
        "Image": "images/Currports ping",
        "Price": 300.00
},

{
    "Id": 17,
        "Name": "ClamWin",
        "Bought": 200,
        "Stock": 100,
        "Company": "Clamwin inc",
        "Desc": " Removes Malware ",
        "Duration": "20m",
        "Type": "Security Tool",
        "Experience": "Expert",
        "Image": "images/ClamWin ping",
        "Price": 300.00
},

{
    "Id": 18,
        "Name": "Regshot",
        "Bought": 200,
        "Stock": 100,
        "Company": "Regshot inc",
        "Desc": " Compares registry entries before + after in/unstalling programs ",
        "Duration": "20m",
        "Type": "Security Tool",
        "Experience": "Expert",
        "Image": "images/Regshot ping",
        "Price": 300.00
},

{
    "Id": 19,
        "Name": "WinPatrol",
        "Bought": 200,
        "Stock": 100,
        "Company": "Winpatrol inc",
        "Desc": " looks for programs running in the background ",
        "Duration": "20m",
        "Type": "Security Tool",
        "Experience": "Expert",
        "Image": "images/WinPatrol ping",
        "Price": 300.00
},

{
    "Id": 20,
        "Name": "TCP view",
        "Bought": 200,
        "Stock": 100,
        "Company": "TCP View inc",
        "Desc": " Port monitoring tool ",
        "Duration": "20m",
        "Type": "Security Tool",
        "Experience": "Expert",
        "Image": "images/TCP View ping",
        "Price": 300.00
}];
